name: Deploy VoidTales Portal

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # 1. Definiere ein Environment für den Job
    environment:
      name: production
      url: https://portal.voidtales.win/

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3
        with:
          # Stellt sicher, dass das Projekt in den richtigen Ordner geklont wird
          path: 'voidtales-portal'

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Cache Node.js modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: voidtales-portal/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/voidtales-portal/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 🧩 Install Dependencies
        run: npm install
        working-directory: './voidtales-portal'

      - name: 🔨 Build Nuxt Project
        run: npm run build
        working-directory: './voidtales-portal'

      - name: 🔨 Start Nuxt Project
        id: 'laststep'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DIFFUSER_USERNAME }}
          key: ${{ secrets.DIFFUSER_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/blogadmin/voidtales-portal
            pm2 start ecosystem.config.cjs
            echo "✅ Deployment erfolgreich abgeschlossen."
